// PENGATURAN LOGIN
// Aplikasi ini berjalan murni di browser (tanpa server), jadi siapapun
// yang buka file ini secara teknis bisa lihat username/password di bawah.
// Cocok untuk "1 akun per pembeli", bukan untuk data rahasia.
const AKUN_VALID = [
  { username: "to", password: "go" },
  { username: "on", password: "go" },
  { username: "for", password: "go" },
  { username: "okay", password: "go" },
  { username: "brow", password: "go" },
  { username: "lets", password: "go" },
  { username: "not", password: "go" },
  { username: "are", password: "go" },
  { username: "but", password: "go" },
  { username: "had", password: "go" },
  { username: "her", password: "go" },
  { username: "his", password: "go" },
  { username: "one", password: "go" },
  { username: "our", password: "go" },
  { username: "she", password: "go" },
  { username: "the", password: "go" },
  { username: "was", password: "go" },
  { username: "who", password: "go" },
  { username: "all", password: "go" },
  { username: "any", password: "go" },
  { username: "can", password: "go" },
  { username: "day", password: "go" },
  { username: "end", password: "go" },
  { username: "few", password: "go" },
  { username: "get", password: "go" },
  { username: "god", password: "go" },
  { username: "got", password: "go" },
  { username: "let", password: "go" },
  { username: "man", password: "go" },
  { username: "new", password: "go" },
  { username: "now", password: "go" },
  { username: "old", password: "go" },
  { username: "out", password: "go" },
  { username: "own", password: "go" },
  { username: "see", password: "go" },
  { username: "warm", password: "go" },
  { username: "sun", password: "go" },
  { username: "two", password: "go" },
  { username: "way", password: "go" },
  { username: "why", password: "go" },
  { username: "yes", password: "go" },
  { username: "able", password: "go" },
  { username: "back", password: "go" },
  { username: "best", password: "go" },
  { username: "call", password: "go" },
  { username: "city", password: "go" },
  { username: "cold", password: "go" },
  { username: "come", password: "go" },
  { username: "dark", password: "go" },
  { username: "door", password: "go" },
  { username: "down", password: "go" },
  { username: "each", password: "go" },
  { username: "easy", password: "go" },
  { username: "even", password: "go" },
  { username: "ever", password: "go" },
  { username: "eyes", password: "go" },
  { username: "face", password: "go" },
  { username: "fact", password: "go" },
  { username: "fair", password: "go" },
  { username: "fall", password: "go" },
  { username: "fast", password: "go" },
  { username: "feel", password: "go" },
  { username: "feet", password: "go" },
  { username: "fill", password: "go" },
  { username: "find", password: "go" },
  { username: "fire", password: "go" },
  { username: "fish", password: "go" },
  { username: "five", password: "go" },
  { username: "food", password: "go" },
  { username: "foot", password: "go" },
  { username: "form", password: "go" },
  { username: "four", password: "go" },
  { username: "free", password: "go" },
  { username: "from", password: "go" },
  { username: "full", password: "go" },
  { username: "give", password: "go" },
  { username: "goes", password: "go" },
  { username: "gold", password: "go" },
  { username: "good", password: "go" },
  { username: "grew", password: "go" },
  { username: "hand", password: "go" },
  { username: "hard", password: "go" },
  { username: "head", password: "go" },
  { username: "hear", password: "go" },
  { username: "heat", password: "go" },
  { username: "held", password: "go" },
  { username: "high", password: "go" },
  { username: "hold", password: "go" },
  { username: "hour", password: "go" },
  { username: "idea", password: "go" },
  { username: "into", password: "go" },
  { username: "just", password: "go" },
  { username: "keep", password: "go" },
  { username: "kind", password: "go" },
  { username: "knew", password: "go" },
  { username: "know", password: "go" },
  { username: "land", password: "go" },
  { username: "last", password: "go" },
  { username: "late", password: "go" },
  { username: "lead", password: "go" },
  { username: "left", password: "go" },
  { username: "life", password: "go" },
  { username: "line", password: "go" },
  { username: "live", password: "go" }
];

// DEVICE LOCK — cek device via npoint.io (soft-lock, bisa dilewati orang
// yang niat buka DevTools). Kalau npoint.io tidak terjangkau, sistem
// fail-open (login tetap diizinkan) supaya pembeli sah tidak ikut terkunci.
const DEVICE_LOCK = {
  npointUrl: "https://api.npoint.io/ee30229b90131df1b572"
};
